config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews, shallow: true
  end

  namespace :admin do
    resources :restaurants, only: :index
  end

  root to: "restaurants#index"


  # collection do
  #   get 'top', to: "restaurants#top"
  #   get 'worst',to: "restaurants#worst"
  # end
  # member do
  #   get 'chef', to: "restaurants#chef"
  # end
  # get 'restaurants/top', to: "restaurants#top"
  # get 'restaurants/:id/chef', to: "restaurants#chef"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end



# get 'reviews/new'
# post 'reviews'

# get 'restaurants/:restaurant_id/reviews/new'
# post 'restaurants/:restaurant_id/reviews'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, uniqueness: true
  validates :address, presence: true
  validates :stars, inclusion: { in: [1, 2, 3, 4, 5] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, length: {minimum: 30, message: "too short. your review sucks, write a longer one"}
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def index
    # Let's anticipate on next week (with login)
    @restaurants = current_user.restaurants
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  def top
    @restaurants = Restaurant.where(stars: 5)
  end

  def worst
    @restaurants = Restaurant.where(stars: 1)
  end

  def chef

    # restaurants/42/chef
    # @restaurant = Restaurant.find(params[:id])
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # create an empty object we can fill out in the form
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])

  end

  def create
    # filled out form for review
    @review = Review.new(review_params)
    # find restaurant params from url
    @restaurant = Restaurant.find(params[:restaurant_id])
    # assign restaurant to review
    @review.restaurant_id = @restaurant.id
    # SAVE the review
    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonPretty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant_list.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stars</th>
      <th>Chef</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.stars %></td>
        <td><%= restaurant.chef %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/chef.html.erb
<h1>The long biography of <%= @restaurant.chef %></h1>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Restaurants</h1>
<%= render 'restaurant_list' %>
<br>
<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>
<p>
  <strong>Stars:</strong>
  <%= @restaurant.stars %>
</p>
<p>Read the reviews~!</p>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %>
    </li>
  <% end %>
</ul>
<%= link_to "Add a review~",  new_restaurant_review_path(@restaurant)  %> | 
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/top.html.erb
<h1>The best rated restaurants on our app</h1>
<%= render 'restaurant_list' %>

app/views/restaurants/worst.html.erb
<h1>This will probably give you laduzi</h1>
<%= render 'restaurant_list' %>

app/views/reviews/new.html.erb
<h1>Add a review!</h1>
<!-- <form action="/restaurants/42/reviews" method="post">
  <input type="" name="">
</form> -->
<!-- post 'restaurants/:restaurant_id/reviews' -->
<!-- post 'reviews' -->
<%= simple_form_for [@restaurant, @review] do |f| %>
  <% if @review.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :content %>
  <%#= f.association :restaurant %>
  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<%= @review.content %>
<p><%= @review.restaurant.name %></p>